services:
  - type: web
    name: nirapoth-backend
    runtime: node
    region: singapore
    plan: free
    branch: main
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true
